[build]
  command = "go run ./server.go"
  functions = "functions"
  publish = "build-output/"

[build.environment]
  GO_IMPORT_PATH = "github.com/fazarth/sipil_api"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/*"
  status = 200