[build]
  command = "build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/fazarth/sipil_api"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/*"
  status = 200