[build]
  command = "make build"
  functions = "functions"
  publish = "site"

[build.environment]
  GO_IMPORT_PATH = "github.com/fazarth/sipil_api"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200